### ISSUE TITLE
boot issue with external drives attached

### ISSUE THREAD

**Issue by beckga** [amahi/disk-wizard#19]
My Amahi server (with Fedora 21) has been working well for a year with an added external hd.  I had no issues when I added the original ext. hd with disk wizard.  Now,  I attempted to use disk wizard to add 1 more external hard drive, and it appeared to work when I added it from the wizard.

The problem is that Amahi will not boot when both external drives are connected to the server - I just get a flashing cursor.  

If I disconnect the new ext hd and boot the server (leaving the original ext hd that I added last year attached), it shows the white bar at the bottom and Fedora 21 to the right of that, and eventually it goes to emergency mode.  I'm not sure why.

If I then press CTRL D to reboot Amahi, and wait until the booting bar is moving to the right on the bottom of the screen and then plug in the original ext. hd,, then it boots with the following error message, although I can access files on Amahi and the ext HD (the one I added last year).  Here is the error message:

```
sd 5:0:0:0 [sdb] Asking for cache data failed
sd 5:0:0:0 [sdb] Assuming drive cache:  write through
```

Prior to using Disk Wizard this time, I never had an issue when the server rebooted - I usually have to do that if we have an internet outage.  I'd appreciate any suggestions so that I can get this working correctly and be able to use disk wizard to add my 2nd external hd. 

Thanks very much - I hope I included enough detail.

**Comment by cpg** [comment]
While the progress bar is moving at boot time, you can press ESC and see where things are at any time. It may give you some insight as to where things are.

Also, you may want to check your `/etc/fstab` file. It may be a little hard to read, but each line has one partition. If a partition listed there is not available at boot time, it will not be mounted.

It is weird that you appear to have the opposite issue -- when an external drive *is* present, it does not boot. An error for this would help. The error you list is not too helpful, as that is from the end of the boot and you were inserting things in the middle.

**Comment by beckga** [comment]
Thanks cpg - I'm new using Fedora.  The Amahi seemed to be an easy way to go for a home server, so I could use a little extra direction from you.  I checked the etc/fstab file as you suggested and the problem appears to be that the external drive I tried to add is still showing in this file.  Once I SSH'd to the server, I don't seem to be having a boot issue anymore - I need to remove the highlighted drive shown on the attached screen shot (Sea 2T) - could you give me instructions on how to do that please? Thanks very much!

![amahi ext drive issue](https://cloud.githubusercontent.com/assets/18474165/25077731/8d8556c2-22fa-11e7-9283-29e678214e52.PNG)

**Comment by beckga** [comment]
Also - the SEA 2T drive no longer shows up under setup/disks/partitions, and it will not allow me to add it using the disk wizard, so hopefully these lines can be removed from the etc/fstab file.  Thanks again...

**Comment by tmkasun** [comment]
Hi @beckga ,

According to the attached screenshot, it seems that `/etc/fstab` file is corrupted since it has some device entries prepends to it.while those should be [appended](https://github.com/amahi/disk-wizard/blob/master/lib/fstab.rb#L85) to the existing fstab entries.
And also it seems you have added two disks through the disk wizard (Disks ending with UUID ...c318 and UUID 1e56), and surprisingly device entry for disk ending with UUID ...1e56 has added twice and one has added in the beginning of the `/etc/fstab`.
IMHO, what you could do to recover from the boot freezes is to restore the `/etc/fstab` file from one of its backups.You could find the [backup](https://github.com/amahi/disk-wizard/blob/master/lib/fstab.rb#L321) file in the `/etc/` directory with some trailing numbers.

**Comment by beckga** [comment]
I had trouble finding how to restore that file, however, I was able to edit the  fstab file and now everything is working well and I was able to add the new external drive.  Thanks for your info - it helped me to get things working again.  :)
